feat: update progress
- Resolve error "ImportError: cannot import name 'convert_router' from partially initialized module 'src.routers.convert' (most likely due to a circular import) (/app/src/routers/convert.py" for `gateway` component
- Resolve error "TypeError: unsupported operand type(s) for +: 'int' and 'str'" for `gateway` component