feat: update progress
- Resolved error `AttributeError: 'URL' object has no attribute 'decode'` for `gateway` component. This is caused by forgetting to convert to string version of request.url. request.url is an URL object.
- Resolved error `httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.` for `gateway` component. Added `SERVER_PROTOCOL` to .env.example file for this reason.